name: 'react setup'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
          with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Delete prepare script
      - run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn run ci:lint
      - name: Run typecheck
        run: yarn run typecheck
      - name: Run tests
        run: yarn run ci:test
